##############################################
# Make File Spec
# https://www.gnu.org/software/make/
# https://www.gnu.org/software/make/manual/html_node/Special-Targets.html
##############################################

##############################################
# EZE DEV PACKAGE COMMANDS
##############################################

# build and install eze package and docker image
docker:
	docker build --tag eze-dev .

.DEFAULT_GOAL := docker
