# ========================================
# EXAMPLE SECRETS TOOL CONFIG
# ========================================

[trufflehog]
SOURCE = "."
INCLUDE_FULL_REASON = true
REPORT_FILE = "../reports/secrets/trufflehog-report.json"
IGNORED_FILES = [
    "eze_report.json"
]

[trufflehog.ci]
INCLUDE_FULL_REASON = false

[gitleaks]
SOURCE = "."
INCLUDE_FULL_REASON = true
REPORT_FILE = "../reports/secrets/gitleaks-report.json"
IGNORED_FILES = [
    "eze_report.json"
]

[gitleaks.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================

[console]
PRINT_SUMMARY_ONLY = true

[json]
REPORT_FILE = "../reports/secrets/eze_report.json"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "gitleaks"]
reporters = ["console", "json"]

[scan.ci]
tools = ["trufflehog:ci", "gitleaks"]
reporters = ["console", "json", "bom"]
