# ========================================
# EXAMPLE MONO REPO TOOL CONFIG
# ========================================

# WIP

# ========================================
# REPORT CONFIG
# ========================================
[bom]
REPORT_FILE = ".eze/monorepo/report-cyclonedx-sbom.json"

[console]
PRINT_SUMMARY_ONLY = true

[json]
REPORT_FILE = ".eze/monorepo/eze_report.json"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = [
]
reporters = ["json", "console", "bom"]

[scan.linux]
tools = [
]
