import pytest

from tests.__fixtures__.fixture_helper import convert_to_std_object
from eze.utils.purl import purl_to_components

cyclone_dx_test_cases = [
    {
        "description": "valid maven purl",
        "purl": "pkg:maven/org.apache.commons/io@1.3.4",
        "canonical_purl": "pkg:maven/org.apache.commons/io@1.3.4",
        "type": "maven",
        "namespace": "org.apache.commons",
        "name": "io",
        "version": "1.3.4",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "basic valid maven purl without version",
        "purl": "pkg:maven/org.apache.commons/io",
        "canonical_purl": "pkg:maven/org.apache.commons/io",
        "type": "maven",
        "namespace": "org.apache.commons",
        "name": "io",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "valid go purl without version and with subpath",
        "purl": "pkg:GOLANG/google.golang.org/genproto#/googleapis/api/annotations/",
        "canonical_purl": "pkg:golang/google.golang.org/genproto#googleapis/api/annotations",
        "type": "golang",
        "namespace": "google.golang.org",
        "name": "genproto",
        "version": None,
        "qualifiers": None,
        "subpath": "googleapis/api/annotations",
        "is_invalid": False,
    },
    {
        "description": "valid go purl with version and subpath",
        "purl": "pkg:GOLANG/google.golang.org/genproto@abcdedf#/googleapis/api/annotations/",
        "canonical_purl": "pkg:golang/google.golang.org/genproto@abcdedf#googleapis/api/annotations",
        "type": "golang",
        "namespace": "google.golang.org",
        "name": "genproto",
        "version": "abcdedf",
        "qualifiers": None,
        "subpath": "googleapis/api/annotations",
        "is_invalid": False,
    },
    {
        "description": "valid go purl with namespace that has a forward slash",
        "purl": "pkg:golang/github.com/etcd-io/etcd@v2.4.0",
        "canonical_purl": "pkg:golang/github.com/etcd-io/etcd@v2.4.0",
        "type": "golang",
        "namespace": "github.com/etcd-io",
        "name": "etcd",
        "version": "v2.4.0",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "debian can use qualifiers",
        "purl": "pkg:deb/debian/curl@7.50.3-1?arch=i386&distro=jessie",
        "canonical_purl": "pkg:deb/debian/curl@7.50.3-1?arch=i386&distro=jessie",
        "type": "deb",
        "namespace": "debian",
        "name": "curl",
        "version": "7.50.3-1",
        "qualifiers": "arch=i386&distro=jessie",  # {"arch": 'i386', "distro": 'jessie'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "docker uses qualifiers and hash image id as versions",
        "purl": "pkg:docker/customer/dockerimage@sha256:244___d9c?repository_url=gcr.io",  # nosecret
        "canonical_purl": "pkg:docker/customer/dockerimage@sha256:244___d9c?repository_url=gcr.io",  # nosecret
        "type": "docker",
        "namespace": "customer",
        "name": "dockerimage",
        "version": "sha256:244___d9c",  # nosecret
        "qualifiers": "repository_url=gcr.io",  # {"repository_url": 'gcr.io'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "Java gem can use a qualifier",
        "purl": "pkg:gem/jruby-launcher@1.1.2?Platform=java",
        "canonical_purl": "pkg:gem/jruby-launcher@1.1.2?platform=java",
        "type": "gem",
        "namespace": None,
        "name": "jruby-launcher",
        "version": "1.1.2",
        "qualifiers": "platform=java",  # {"platform": 'java'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "maven often uses qualifiers",
        "purl": "pkg:Maven/org.apache.xmlgraphics/batik-anim@1.9.1?classifier=sources&repositorY_url=repo.spring.io/release",
        "canonical_purl": "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?classifier=sources&repository_url=repo.spring.io/release",
        "type": "maven",
        "namespace": "org.apache.xmlgraphics",
        "name": "batik-anim",
        "version": "1.9.1",
        "qualifiers": "classifier=sources&repository_url=repo.spring.io/release",
        # {"classifier": 'sources', "repository_url": 'repo.spring.io/release'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "maven pom reference",
        "purl": "pkg:Maven/org.apache.xmlgraphics/batik-anim@1.9.1?extension=pom&repositorY_url=repo.spring.io/release",
        "canonical_purl": "pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?extension=pom&repository_url=repo.spring.io/release",
        "type": "maven",
        "namespace": "org.apache.xmlgraphics",
        "name": "batik-anim",
        "version": "1.9.1",
        "qualifiers": "extension=pom&repository_url=repo.spring.io/release",
        # {"extension": 'pom', "repository_url": 'repo.spring.io/release'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "maven can come with a type qualifier",
        "purl": "pkg:Maven/net.sf.jacob-project/jacob@1.14.3?classifier=x86&type=dll",
        "canonical_purl": "pkg:maven/net.sf.jacob-project/jacob@1.14.3?classifier=x86&type=dll",
        "type": "maven",
        "namespace": "net.sf.jacob-project",
        "name": "jacob",
        "version": "1.14.3",
        "qualifiers": "classifier=x86&type=dll",  # {"classifier": 'x86', "type": 'dll'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "npm can be scoped",
        "purl": "pkg:npm/%40angular/animation@12.3.1",
        "canonical_purl": "pkg:npm/%40angular/animation@12.3.1",
        "type": "npm",
        "namespace": "@angular",
        "name": "animation",
        "version": "12.3.1",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "nuget names are case sensitive",
        "purl": "pkg:Nuget/EnterpriseLibrary.Common@6.0.1304",
        "canonical_purl": "pkg:nuget/EnterpriseLibrary.Common@6.0.1304",
        "type": "nuget",
        "namespace": None,
        "name": "EnterpriseLibrary.Common",
        "version": "6.0.1304",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "pypi names have special rules and not case sensitive",
        "purl": "pkg:PYPI/Django_package@1.11.1.dev1",
        "canonical_purl": "pkg:pypi/django-package@1.11.1.dev1",
        "type": "pypi",
        "namespace": None,
        "name": "django-package",
        "version": "1.11.1.dev1",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "rpm often use qualifiers",
        "purl": "pkg:Rpm/fedora/curl@7.50.3-1.fc25?Arch=i386&Distro=fedora-25",
        "canonical_purl": "pkg:rpm/fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25",
        "type": "rpm",
        "namespace": "fedora",
        "name": "curl",
        "version": "7.50.3-1.fc25",
        "qualifiers": "arch=i386&distro=fedora-25",  # {"arch": 'i386', "distro": 'fedora-25'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "a scheme is always required",
        "purl": "EnterpriseLibrary.Common@6.0.1304",
        "canonical_purl": "EnterpriseLibrary.Common@6.0.1304",
        "type": None,
        "namespace": None,
        "name": "EnterpriseLibrary.Common",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": True,
    },
    {
        "description": "a type is always required",
        "purl": "pkg:EnterpriseLibrary.Common@6.0.1304",
        "canonical_purl": "pkg:EnterpriseLibrary.Common@6.0.1304",
        "type": None,
        "namespace": None,
        "name": "EnterpriseLibrary.Common",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": True,
    },
    {
        "description": "a name is required",
        "purl": "pkg:maven/@1.3.4",
        "canonical_purl": "pkg:maven/@1.3.4",
        "type": "maven",
        "namespace": None,
        "name": None,
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": True,
    },
    {
        "description": "slash / after scheme is not significant",
        "purl": "pkg:/maven/org.apache.commons/io",
        "canonical_purl": "pkg:maven/org.apache.commons/io",
        "type": "maven",
        "namespace": "org.apache.commons",
        "name": "io",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "double slash // after scheme is not significant",
        "purl": "pkg://maven/org.apache.commons/io",
        "canonical_purl": "pkg:maven/org.apache.commons/io",
        "type": "maven",
        "namespace": "org.apache.commons",
        "name": "io",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "slash /// after type  is not significant",
        "purl": "pkg:///maven/org.apache.commons/io",
        "canonical_purl": "pkg:maven/org.apache.commons/io",
        "type": "maven",
        "namespace": "org.apache.commons",
        "name": "io",
        "version": None,
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "valid maven purl with case sensitive namespace and name",
        "purl": "pkg:maven/HTTPClient/HTTPClient@0.3-3",
        "canonical_purl": "pkg:maven/HTTPClient/HTTPClient@0.3-3",
        "type": "maven",
        "namespace": "HTTPClient",
        "name": "HTTPClient",
        "version": "0.3-3",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "valid maven purl containing a space in the version and qualifier",
        "purl": "pkg:maven/mygroup/myartifact@1.0.0%20Final?mykey=my%20value",
        "canonical_purl": "pkg:maven/mygroup/myartifact@1.0.0%20Final?mykey=my%20value",
        "type": "maven",
        "namespace": "mygroup",
        "name": "myartifact",
        "version": "1.0.0 Final",
        "qualifiers": "mykey=my value",  # {"mykey": 'my value'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "checks for invalid qualifier keys",
        "purl": "pkg:npm/myartifact@1.0.0?in%20production=true",
        "canonical_purl": "pkg:npm/myartifact@1.0.0?in%20production=true",
        "type": "npm",
        "namespace": None,
        "name": "myartifact",
        "version": "1.0.0",
        "qualifiers": "in production=true",  # {'in production': 'true'},
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "namespace can contain special characters",
        "purl": "pkg:npm/%40foo%40%3F%23/bar@1.0.0",
        "canonical_purl": "pkg:npm/%40foo%40%3F%23/bar@1.0.0",
        "type": "npm",
        "namespace": "@foo@?#",
        "name": "bar",
        "version": "1.0.0",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "name can contain special characters (with namespace)",
        "purl": "pkg:npm/%40foo/bar%40%3F%23@1.0.0",
        "canonical_purl": "pkg:npm/%40foo/bar%40%3F%23@1.0.0",
        "type": "npm",
        "namespace": "@foo",
        "name": "bar@?#",
        "version": "1.0.0",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "name can contain special characters (without namespace)",
        "purl": "pkg:npm/bar%40%3F%23@1.0.0",
        "canonical_purl": "pkg:npm/bar%40%3F%23@1.0.0",
        "type": "npm",
        "namespace": None,
        "name": "bar@?#",
        "version": "1.0.0",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
    {
        "description": "version can contain special characters",
        "purl": "pkg:npm/%40foo/bar@1.0.0-%40%3F%23",
        "canonical_purl": "pkg:npm/%40foo/bar@1.0.0-%40%3F%23",
        "type": "npm",
        "namespace": "@foo",
        "name": "bar",
        "version": "1.0.0-@?#",
        "qualifiers": None,
        "subpath": None,
        "is_invalid": False,
    },
]


@pytest.mark.parametrize("test_data", cyclone_dx_test_cases)
def test_purl_to_components(test_data):
    # Given
    input_purl = test_data["canonical_purl"]
    expected_output = {
        "full_name": f"{test_data['namespace']}/{test_data['name']}" if test_data["namespace"] else test_data["name"],
        "name": test_data["name"],
        "namespace": test_data["namespace"],
        "qualifiers": test_data["qualifiers"],
        "scheme": "pkg",
        "subpath": test_data["subpath"],
        "type": test_data["type"],
        "version": test_data["version"],
    }
    # When
    output = purl_to_components(input_purl)
    # Then
    if test_data["is_invalid"]:
        assert output is None
        return
    assert convert_to_std_object(output) == expected_output
